### PR TITLE
ensure conda execution is enabled in configuration

### PR DESCRIPTION
**Pull request by cpauvert**
Hi,
Here's a tentative PR for #4, but in the issue I was misleading in trying to change how the command line for nextflow was called, when in fact, the key was in the configuration file.

I ensure that conda is enabled as per https://www.nextflow.io/docs/stable/config.html#config-conda

Let me know if you prefer edits to be made differently.
Best,

### CODE REVIEW

**Comment by cpauvert** [comment]
It seems the issue for the checks is about the rate limit for codecov. 

```
There was an error fetching the storage URL during POST
ErrorDetail(string='Rate limit reached. Please upload with 
the Codecov repository upload token to resolve issue.
```
The code coverage report seems to be correctly generated in the ubuntu image but I do not know how to fetch this report. Any suggestions?

BEst,

**Comment by beardymcjohnface** [comment]
Yeah, I had this issue with another repo of mine. Let me push an update real quick.

**Comment by beardymcjohnface** [comment]
Hi @cpauvert can you update your PR branch please?

**Comment by cpauvert** [comment]
> Hi @cpauvert can you update your PR branch please?

Yep, done! Thanks for the fix

**Comment by beardymcjohnface** [comment]
Awesome, thanks!

**Pull request merged**
